version: "3"
services:
  # ==========================================================================
  # NOTE: Used Github as source repo for demo purpose
  #
  # gitlab:
  #  container_name: "gitlab"
  #  build: "./gitlab"
  #  ports:
  #    - 14200:80
  #  volumes:
  #    - local-data:/home/gitlab
  #  networks:
  #    - cicdnet
  #  restart: always

  # ==========================================================================
  jenkins:
    container_name: "jenkins"
    build: "./jenkins"
    ports:
      - 14300:8080
    volumes:
      - local-data:/home/jenkins
    networks:
      - cicdnet
    environment:
      - JENKINS_HOME=/home/jenkins
    #depends_on:
    #  - "gitlab"
    restart: always

  # ==========================================================================
  # u: admin | p: data/admin.password
  nexus:
    container_name: "nexus"
    build: "./nexus"
    ports:
      - 8081:8081
    volumes:
      - local-data:/nexus-data
    networks:
      - cicdnet
    depends_on:
      - "jenkins"
    restart: always

  # ==========================================================================
  registry:
    container_name: "docker_registry"
    build: "./docker_registry"
    ports:
      - 5000:5000
    networks:
      - cicdnet
    restart: always

  # ==========================================================================
  # u: admin | p: admin
  sonar:
    container_name: "sonar"
    build: "./sonar"
    ports:
      - 9000:9000
    volumes:
      - local-data:/opt/sonarqube/data
    networks:
      - cicdnet
    restart: always

  # ==========================================================================
  consul:
    container_name: "consul"
    build: "./consul"
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - local-data:/opt/sonarqube/data
    networks:
      - cicdnet
    restart: always

  # ==========================================================================
  # u: admin | p: admin
  grafana:
    container_name: "grafana"
    build: "./grafana"
    ports:
      - 3000:3000
    networks:
      - cicdnet
    restart: always

  # ==========================================================================
  # u: admin | p: Admin2019 (admin was not used because there are some password restriction rules)
  splunk:
    container_name: "splunk"
    build: "./splunk"
    ports:
      - 8000:8000
      - 25600:25600
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Admin2019
    networks:
      - cicdnet
    restart: always

  # ==========================================================================
  prometheus:
    container_name: "prometheus"
    build: "./prometheus"
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - cicdnet
    depends_on:
      - "grafana"
    restart: always

# ==========================================================================
# NETWORK
networks:
  cicdnet:

# ==========================================================================
# VOLUMES
volumes:
  local-data:
    driver: local
    driver_opts:
      type: none
      device: /home/smiguelnet/cicd-data
      o: bind
