---
- hosts: all
  tasks:
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

    - name: Install list of packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "docker-ce"]
        state: present
        update_cache: yes
    - name: Install pip
      apt:
        name: ["python3", "python-pip", "python3-pip"]
        state: present
        update_cache: yes
    - pip:
        name: docker-py
        executable: pip3
        state: latest
    - pip:
        name: docker-compose
        executable: pip3
        state: latest
