FROM prom/prometheus

LABEL maintainer="Sergio Miguel <sergio@smiguelnet>"
LABEL service.name="Prometheus"
LABEL service.version="1.0.0"
COPY ./prometheus.yml /etc/prometheus/prometheus.yml

EXPOSE 9090